#! /usr/bin/env bash



function mvplay() {
	
	folder_dependencies
	printf "\n";
	echo "***********************************";
	echo '* 1. Download Videos & Playlist   *';
	echo '* 2. Download Musics              *';
	echo "***********************************";

	printf "> "	
	read user;
	
	if [ $user == '1' ]; then
		videos

	elif [ $user == '2' ]; then
		musics

	else
		echo "Invalid Option";
		mvplay
	fi

}


folder_dependencies() {

	directories=("$PWD/MvPlay/" "$PWD/MvPlay/Musics/" "$PWD/MvPlay/Videos/" "$PWD/MvPlay/Videos/Playlists/");
	for i in ${directories[@]};
	do
		if [ ! -d $i ];
		then
			mkdir $i;
		fi
	done
}

videos() {

	printf "\nlink:";
	printf "\n> ";
	read link_yt
	if echo $link_yt | grep -e '/playlist?'; then
		echo "OK";
		download_playlist


	elif echo $link_yt | grep -e '/watch?v\|youtu.be'; then
		echo "OK";
		download_videos


	else
		printf "\nNOT A LINK\n";
		videos
	fi

}

download_playlist() {

	# download playlist and put it in a folder
	./bin/youtube-dl --ignore-config --yes-playlist -w -i -o "$PWD/MvPlay/Videos/Playlists/playlist_%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" $link_yt
		
	if echo $? == 0; then
		printf "\n\nSuccess!!!"


	else 
		printf "\nSomething is wrong...";
		mvplay
	fi

}


download_videos() {

	# download video and put in a folder
	./bin/youtube-dl --ignore-config -w -i -o "$PWD/MvPlay/Videos/%(title)s.%(ext)s" $link_yt 

	if echo $? == 0; then
		printf "\n\nSuccess!!!"	


	else
		printf "\nSomething is wrong...";
		mvplay
	fi

}


musics() {

	printf "\nlink:";
	printf "\n> ";

	# take links from standard input
	read link_stdin


	if echo $link_stdin | grep -e '/playlist?'; then
		echo "OK";
		download_music_playlist


	elif echo $link_stdin | grep -e '/watch?v\|youtu.be'; then
		echo "OK";
		download_music


	else
		printf "\nNOT A LINK\n";
		musics	
	fi

}


download_music_playlist() {

	# download musics convert to mp3 and put it in a folder
	./bin/youtube-dl --ignore-config --yes-playlist -w -i -x --audio-quality 5 --audio-format "mp3" -o "$PWD/MvPlay/Musics/%(title)s.%(ext)s" $link_stdin
	
	if echo $? == 0; then
		printf "\n\nSuccess!!!";	


	else
		printf "\nSomething is wrong...";
		mvplay
	fi
}


download_music() {
	
	# donwload music convert to mp3 and put in a folder
	./bin/youtube-dl --ignore-config --no-playlist -w -i -x --audio-quality 5 --audio-format "mp3" -o "$PWD/MvPlay/Musics/%(title)s.%(ext)s" $link_stdin


	if echo $? == 0; then
		printf "\n\nSuccess!!!";	


	else
		printf "\nSomething is wrong...";
		mvplay
	fi

}

mvplay
